// angular-apps/happiest-minds/src/app/employee-form/employee-form.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Employee } from '../Employee';
import { EmployeeApiService } from '../employee-api.service';
import { EmployeeStorage } from '../EmployeeStorage';

@Component({
  selector: 'app-employee-form',
  templateUrl: './employee-form.component.html',
  styleUrls: ['./employee-form.component.css']
})
export class EmployeeFormComponent implements OnInit {

  constructor(private _employeeClient:EmployeeApiService, 
                private _router:Router) {
                  console.log("Employee Form Component Loaded")
                 }

  ngOnInit(): void {
  }

  saveEmployee(employee:Employee){
    this._employeeClient.saveEmployee(employee)
                  .subscribe(data=>this._router.navigate(['/view-employee']))
  }

}

<h2>Input Employee Details</h2>
<form (submit)="saveEmployee(employeeForm.value)" #employeeForm="ngForm">
   <div class="form-group">
    <label for="employeeId">Employee ID</label>
    <input ngModel required minlength="5" class="form-control" type="text" 
               #t_employeeId="ngModel" name="employeeId" id="employeeId"
               [class.is-invalid]="t_employeeId.invalid && t_employeeId.touched"
               [class.is-valid]="t_employeeId.valid">
    <p *ngIf="t_employeeId.touched && t_employeeId.invalid" class="text-danger"> 
        <small *ngIf="t_employeeId.errors?.['required']">ID is required</small>
        <small *ngIf="t_employeeId.errors?.['minlength']">ID should have atleast 5 digits</small>
    </p>
   
   </div>
   <div class="form-group">
    <label for="employeeName">Employee Name</label>
    <input ngModel required minlength="3" pattern="[a-zA-Z\s]+" class="form-control" type="text" 
                name="employeeName" id="employeeName" #t_employeeName="ngModel">
    <p *ngIf="t_employeeName.touched && t_employeeName.invalid" class="text-danger"> Errors</p>
   </div>
   <div class="form-group">
    <label for="email">Email</label>
    <input ngModel email required class="form-control" type="email" 
                name="email" id="email">
   </div>

   <div class="form-group">
    <label for="joinDate">Date Joined</label>
    <input ngModel required class="form-control" type="date" 
                name="joinDate" id="joinDate">
   </div>
   <div>
   <button [disabled]="employeeForm.invalid" type="submit" class="btn btn-outline-primary">Save Employee</button>
   </div>
</form>

// react-apps/happiest-minds/src/employee/EmployeeForm.js
import React, { Component, PureComponent } from 'react'
import 'bootstrap/dist/css/bootstrap.min.css'
import axios from 'axios'
import { Navigate } from "react-router-dom";


export class EmployeeForm extends Component {

    constructor(props) {
      super(props)
   // this.handleFromInputs=this.handleFromInputs.bind(this)
     // const {employeeId,employeeName,email}=this.props.emp;
      this.state = {
         employeeId:'',
         employeeName:'',
         email:'',
         joinDate:'',
         emailValid:false,
         employeeIdValid:false,
         employeeNameValid:false,
         formValid:false,
         employee:{},
         success:false
      }
    }
    
    componentDidMount(){
      if(this.props.emp){
      const {employeeId,employeeName,email,joinDate}=this.props.emp;
        this.setState({
          employeeId:employeeId,
          employeeName:employeeName,
          email:email,
          joinDate:joinDate,
          emailValid:true,
         employeeIdValid:true,
         employeeNameValid:true,
         formValid:true,

        }
        )
      }
      
    }

    

  render() {

    const employeeIdError = !this.state.employeeIdValid && 
                            <p className='text-danger'>Input a valid Employee ID</p>
    
    // if(this.state.success){
    //   return <Navigate to="/view-employee"/>
    // }
    // else
    return (
      <div>
        <h2>Employee Information</h2>
        <form method='post' onSubmit={(event)=>this.saveEmployeeData(event)}>
           <div className='form-group'>
            <label className='form-label' htmlFor='employeeId'>Employee ID</label>
            <input type='text' 
                name='employeeId' 
                className='form-control' 
                value={this.state.employeeId}
                placeholder='Input Employee ID'
                required
                onChange={(event)=>this.handleFromInputs(event)}
                />
                {employeeIdError}
           </div> 

           <div className='form-group'>
            <label className='form-label' htmlFor='employeeName'>Employee Name</label>
            <input type='text' 
                name='employeeName' 
                className='form-control' 
                value={this.state.employeeName}
                placeholder='Input Employee Name'
                onChange={(event)=>this.handleFromInputs(event)}
                />
           </div> 

           <div className='form-group'>
            <label className='form-label' htmlFor='email'>Email</label>
            <input type='email' 
                name='email' 
                className='form-control' 
                value={this.state.email}
                placeholder='Input Email'
                onChange={(event)=>this.handleFromInputs(event)}
                />
           </div> 

           <div className='form-group'>
            <label className='form-label' htmlFor='joinDate'>Date Joined</label>
            <input type='date' 
                name='joinDate' 
                className='form-control' 
                value={this.state.joinDate}
                placeholder='Input Date Joined'
                onChange={(event)=>this.handleFromInputs(event)}
                />
           </div> 

            <button type='submit' disabled={!this.state.formValid} className='btn btn-primary'>Save Employee</button>

        </form>

      </div>
    )
  }


  handleFromInputs(event){
    const inputName = event.target.name;
    const value = event.target.value;

    this.setState({
        [inputName]:value
    },()=>this.validateInputs(inputName,value))
  }

  validateInputs(input,value){
    let isValid=false;
    switch(input){
        case 'employeeId':
            isValid=value.length>=5 && value.length<=8
            this.setState({
                employeeIdValid:isValid
            })
            break;
        case 'employeeName':
            isValid=value.length>=3
            this.setState({
                employeeNameValid:isValid
            })
            break;
        case 'email':
            isValid=value.length>=8
            this.setState({
                emailValid:isValid
            })
            break;
    }
    this.setState({},()=>this.validateForm())
  }

  validateForm(){
    const formValid = this.state.employeeIdValid && this.state.employeeNameValid && this.state.emailValid;
    this.setState({
        formValid:formValid
    })
  }

  saveEmployeeData(event){
    event.preventDefault();
    const employee = {
      id:this.state.employeeId,
      employeeId:this.state.employeeId,
      employeeName:this.state.employeeName,
      email:this.state.email,
      joinDate:this.state.joinDate
    }
    if(this.props.emp){
      axios.put("http://localhost:8500/employees",employee)
      .then(response=>{
        this.setState({
        employee:response.data,
        success:true
      })
      alert("Employee Updated Successfully")
      this.props.fetchDataFromApi();
    })
      .catch(err=>console.error(err))
      
//this.props.addEmployee(this.state)
}
    else{
    axios.post("http://localhost:8500/employees",employee)
          .then(response=>{
            this.setState({
            employee:response.data,
            success:true
          })
          alert("Employee Added Successfully")
          
        })
          .catch(err=>console.error(err))
          
    //this.props.addEmployee(this.state)
  }
}

}

export default EmployeeForm
